const SET_BOOKS = 'SET_BOOKS'
const LOAD_BOOKS = 'LOAD_BOOKS'
const LOAD_BOOK = 'LOAD_BOOK'
const SET_SELECTED_BOOK = 'SET_SELECTED_BOOK'
const SET_SEARCH="SET_SEARCH"
const SET_PAGE="SET_PAGE"
const COUNT_PAGES="COUNT_PAGES"
const LOAD_SEARCHED_BOOKS = "LOAD_SEARCHED_BOOKS"
const SET_SEARCHED_BOOK = "SET_SEARCHED_BOOK"
const ADD_TO_FAV = 'ADD_TO_FAV'

export {SET_BOOKS, LOAD_BOOKS, LOAD_BOOK, SET_SELECTED_BOOK, SET_SEARCH, SET_PAGE, COUNT_PAGES, LOAD_SEARCHED_BOOKS, SET_SEARCHED_BOOK, ADD_TO_FAV}