const ACTIVATION_REGISTRATION = 'ACTIVATION_REGISTRATION';
const SIGN_UP = 'SIGN_UP';
const SIGN_IN = 'SIGN_IN';
const GET_USER_INFO = 'GET_USER_INFO';
const SET_USER = 'SET_USER'


export {
   ACTIVATION_REGISTRATION,
   SIGN_UP,
   SIGN_IN,
   GET_USER_INFO,
   SET_USER
}